spring:
  datasource:
    # Eclipse Connect localhost
    url: jdbc:postgresql://localhost:5432/shopping_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always # 每次啟動都執行 schema.sql

logging:
  level:
    com.shopping.system.mapper: DEBUG # 開發時顯示 SQL